# Generated by Django 4.2 on 2026-02-26 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_collect', models.CharField(max_length=250, verbose_name='Название сбора')),
                ('event', models.CharField(choices=[('birthday', 'День рождения'), ('beersday', 'День пива'), ('Longtime', 'Долго невиделись'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Повод сбора')),
                ('description', models.TextField(blank=True, verbose_name='Описание сбора')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Текущая сумма сбора')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Целевая сумма сбора')),
                ('donors_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество доноров')),
                ('image', models.URLField(blank=True, verbose_name='Картинка сбора')),
                ('ends_collect', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сбора')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора')),
            ],
            options={
                'verbose_name': 'Общий сбор',
                'verbose_name_plural': 'Сборы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='collects.collect', verbose_name='Общий сбор')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Донор')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'Пожертвования',
            },
        ),
    ]
