# Generated by Django 4.2 on 2026-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collects_images/', verbose_name='Картинка сбора'),
        ),
    ]
